version: "3.7"

services:
  mysql:
    hostname: mysql
    container_name: car_rent_mysql
    image: mysql
    ports:
      - "3306:3306"
    networks:
      - service-network
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: true
  rabbitmq:
    hostname: rabbitmq
    container_name: car_rent_rabbitmq
    image: rabbitmq:3.11-management
    ports:
      - "15672:15672"
      - "5672:5672"
    networks:
      - service-network
  elasticsearch:
    hostname: elasticsearch
    container_name: car_rent_elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.8
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - service-network
    environment:
      discovery.type: single-node

networks:
  service-network:
    name: service-network